DALESURBAN – uDALES
DALESURBAN Program
65 statements
Source File
Uses
modstatsdump
modpois
modsave
modchecksim
modstat_nc
modmpi
modforces
initfac
modsubgrid
modstartup
modthermodynamics
modfielddump
modEB
modboundary
modibm
modglobal
Calls
Contents
Source Code
DALESURBAN
Source Code
program DALESURBAN      !Version 48
!!----------------------------------------------------------------
!!     0.0    USE STATEMENTS FOR CORE MODULES
!!----------------------------------------------------------------
  use modmpi,            only : myid, initmpi
  use modglobal,         only : rk3step,timeleft,ib,jb,kb,ke
  use modstartup,        only : startup,exitmodules
  use modsave,           only : writerestartfiles
  use modboundary,       only : boundary, grwdamp,tqaver
  use modthermodynamics, only : thermodynamics
!  use modsurface,        only : surface
  use modsubgrid,        only : subgrid
  use modforces,         only : forces,coriolis,lstend,fixuinf1,fixuinf2,fixthetainf,nudge, masscorr
  use modpois,           only : poisson
  use modibm,            only : createwalls,ibmwallfun,ibmnorm,nearwall,bottom
  use initfac,           only : readfacetfiles
  use modEB,             only : initEB,EB
!----------------------------------------------------------------
!     0.1     USE STATEMENTS FOR ADDONS STATISTICAL ROUTINES
!----------------------------------------------------------------
  use modchecksim,     only : initchecksim, checksim
  use modstat_nc,      only : initstat_nc
  use modfielddump,    only : initfielddump, fielddump,exitfielddump
  use modstatsdump,    only : initstatsdump,statsdump,exitstatsdump    !tg3315
  !use modbudget,       only : initbudget, budgetstat, exitbudget
  implicit none
!----------------------------------------------------------------
!     1      READ NAMELISTS,INITIALISE GRID, CONSTANTS AND FIELDS
!----------------------------------------------------------------
  call initmpi
  write(*,*) "done initmpi"
  call startup
  write(*,*) "done startup"
!---------------------------------------------------------
!      2     INITIALIZE STATISTICAL ROUTINES AND ADD-ONS
!---------------------------------------------------------
  call initchecksim
  call initstat_nc
  call initfielddump
  call initstatsdump !tg3315
  call readfacetfiles
  call initEB
  write(*,*) "done init stuff"
  write(6,*) 'Determine immersed walls'
  call createwalls    ! determine walls/blocks
 ! call nearwall       ! determine minimum distance and corresponding shear components, ils13 10.07.17, commented, not functional at the moment, not needed for vreman but for smag., fix in modibm
  write(6,*) 'Finished determining immersed walls'
  call boundary  !ils13 22.06.2017 inserted boundary here to get values at ghost cells before iteration starts
!  not necessary but abates the fact that temp field is randomised by randomisation of just velocity fields
!  (because advection at start of time loop without being divergence free)
!  call poisson
!------------------------------------------------------
!   3.0   MAIN TIME LOOP
!------------------------------------------------------
  write(*,*)'START myid ', myid
  do while ((timeleft>0) .or. (rk3step < 3))
    call tstep_update
!-----------------------------------------------------
!   3.2   ADVECTION AND DIFFUSION
!-----------------------------------------------------
    call advection                ! now also includes predicted pressure gradient term
    call subgrid
!-----------------------------------------------------
!   3.3   THE SURFACE LAYER
!-----------------------------------------------------
    call bottom
!-----------------------------------------------------
!   3.4   REMAINING TERMS
!-----------------------------------------------------
    call coriolis       !remaining terms of ns equation
    call forces         !remaining terms of ns equation
    call lstend         !large scale forcings
    call nudge          ! nudge top cells of fields to enforce steady-state
    call ibmwallfun     ! immersed boundary forcing: only shear forces.
    call masscorr       ! correct pred. velocity pup to get correct mass flow
    call ibmnorm        ! immersed boundary forcing: set normal velocities to zero
    call EB
    call scalsource     ! adds continuous forces in specified region of domain
!------------------------------------------------------
!   3.4   EXECUTE ADD ONS
!------------------------------------------------------
    call fixuinf2
    call fixuinf1
!-----------------------------------------------------------------------
!   3.5  PRESSURE FLUCTUATIONS, TIME INTEGRATION AND BOUNDARY CONDITIONS
!-----------------------------------------------------------------------
    call grwdamp        !damping at top of the model
    call poisson
    call tstep_integrate
    call boundary
    call fixthetainf
!-----------------------------------------------------
!   3.6   LIQUID WATER CONTENT AND DIAGNOSTIC FIELDS
!-----------------------------------------------------
    call thermodynamics
!-----------------------------------------------------
!   3.7  WRITE RESTARTFILES AND DO STATISTICS
!------------------------------------------------------
    call checksim
   ! call writedatafiles   ! write data files for later analysis
    call writerestartfiles
    call fielddump
    call statsdump        ! tg3315
  end do
!-------------------------------------------------------
!             END OF TIME LOOP
!-------------------------------------------------------
!--------------------------------------------------------
!    4    FINALIZE ADD ONS AND THE MAIN PROGRAM
!-------------------------------------------------------
  call exitfielddump
  call exitstatsdump     !tg3315
  call exitmodules
end program DALESURBAN
Call graph
dalesurban calls advection, bottom, boundary, checksim, coriolis, createwalls, eb, exitfielddump, exitmodules, exitstatsdump, fielddump, fixthetainf, fixuinf1, fixuinf2, forces, grwdamp, ibmnorm, ibmwallfun, initchecksim, initeb, initfielddump, initmpi, initstat_nc, initstatsdump, lstend, masscorr, nudge, poisson, readfacetfiles, scalsource, startup, statsdump, subgrid, thermodynamics, tstep_integrate, tstep_update, writerestartfiles
advection calls advecc_2nd, advecc_kappa, advecc_upw, advecu_2nd, advecv_2nd, advecw_2nd
bottom calls wfmneutral, wfuno
boundary calls cyclichi, cyclichj, cyclicmi, cyclicmj, cyclicqi, cyclicqj, cyclicsi, cyclicsj, drivergen, fluxtop, fluxtopscal, inletgen, inletgennotemp, inlettop, iohi, iolet, ioqi, iosi, scalrec, scalsirane, valuetop, valuetopscal
checksim calls calccourant, calcdiffnr, chkdiv
eb calls writestat_nc, mpi_bcast, calclw, gaussji, intqh, matinv4, updategr, writestat_1d_nc, writestat_2d_nc
exitfielddump calls exitstat_nc
exitmodules calls exitfields, exitglobal, exitinlet, exitmpi, exitpois, exitsubgrid, exitthermodynamics
fielddump calls writestat_nc
fixuinf1 calls detfreestream
fixuinf2 calls detfreestream
ibmwallfun calls xwallfun, ywallfunmin, ywallfunplus, zwallfun
initchecksim calls mpi_bcast
initeb calls define_nc, gaussji, matinv4, ncinfo, open_nc, writestat_dims_nc
initfielddump calls mpi_bcast, define_nc, ncinfo, open_nc, writestat_dims_nc
initmpi calls mpi_cart_create, mpi_cart_shift, mpi_comm_rank, mpi_comm_size, mpi_dims_create, mpi_init, mpi_wtime
initstatsdump calls mpi_bcast, define_nc, ncinfo, open_nc, writestat_dims_nc
masscorr calls mpi_bcast, sumy_ibm
poisson calls fillps, poisr, solmpj, tderive
readfacetfiles calls mpi_bcast, nf90_get_var, nf90_inq_varid, nf90_open, qsat
startup calls mpi_bcast, calcfluidvolumes, checkinitvalues, createmasks, createscals, initboundary, initdriver, initfields, initglobal, initinlet, initpois, initsubgrid, initthermodynamics, readinitfiles
statsdump calls writestat_nc, avexy_ibm, avey_ibm, tkestatsdump, writestat_1d_nc
subgrid calls closure, diffc, diffe, diffu, diffv, diffw, sources
thermodynamics calls avexy_ibm, calc_halflev, calthv, diagfld, thermo
tstep_integrate calls chem
tstep_update calls mpi_allreduce
writestat_nc calls writestat_1d_nc, writestat_2d_nc, writestat_3d_nc, writestat_3d_short_nc, writestat_time_nc
advecc_kappa calls rlim
avexy_ibm calls mpi_allreduce
avey_ibm calls mpi_allreduce
calccourant calls mpi_allreduce
calcdiffnr calls mpi_allreduce
calcfluidvolumes calls fluidvolume, uoutletarea, voutletarea
checkinitvalues calls mpi_bcast, mpi_finalize
chkdiv calls mpi_allreduce
closure calls closurebc
createmasks calls mpi_allreduce, mpi_bcast
cyclichj calls excjs
cyclicmj calls excjs
cyclicqj calls excjs
cyclicsj calls excjs
define_nc calls nf90_inq_varid, nf90_def_var, nf90_enddef, nf90_inq_dimid, nf90_put_att, nf90_redef, nchandle_error
detfreestream calls mpi_allreduce
diagfld calls avexy_ibm, fromztop
drivergen calls writedriverfile
exitmpi calls mpi_wtime, mpi_comm_free, mpi_finalize
exitstat_nc calls nf90_close, nchandle_error
fillps calls bcpup
initglobal calls mpi_bcast, float
initinlet calls readzincoord
initsubgrid calls subgridnamelist
inletgen calls writerestartfiles, blthicknesst, dispthicknessexp, enthalpythickness, momentumthicknessexp, readinletfile, slabsum, wallawinlet, writeinletfile
inletgennotemp calls writerestartfiles, blthicknesst, dispthicknessexp, momentumthicknessexp, readinletfile, slabsum, wallawinlet, writeinletfile
inlettop calls slabsumi
intqh calls mpi_allreduce
iolet calls slabsum
open_nc calls nf90_get_var, nf90_inq_varid, nf90_open, nf90_create, nf90_def_dim, nf90_def_var, nf90_enddef, nf90_inq_dimid, nf90_inquire, nf90_inquire_dimension, nf90_put_att, nf90_sync
poisr calls blktri, float, all_all_j2, barrou, vrfftb, vrfftf, vrffti
readinitfiles calls boundary, thermodynamics, mpi_bcast, avexy_ibm, calc_halflev, drivergen, randomnize, readdriverfile, readinletfile, readrestartfiles, slabsum
solmpj calls mpi_comm_rank, mpi_comm_size, float, all_all_j, rfftb, rfftf, rffti
sumy_ibm calls mpi_allreduce
tderive calls bcp, slabsum
tkestatsdump calls avexy_ibm, excjs
updategr calls qsat
wfuno calls unoh
writestat_1d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_2d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_dims_nc calls nf90_inq_varid, nf90_inquire_dimension, nf90_put_var
xwallfun calls wfmneutral, wfuno, wfgr, xwallscalar
ywallfunmin calls wfmneutral, wfuno, wfgr, ywallscalarmin
ywallfunplus calls wfmneutral, wfuno, wfgr, ywallscalarplus
zwallfun calls wfmneutral, wfuno, wfgr, zwallscalar
all_all_j calls mpi_alltoall
all_all_j2 calls barrou, mpi_alltoall
barrou calls mpi_barrier
bcp calls excj
bcpup calls excjs
closurebc calls excjs
excjs calls mpi_sendrecv
fluidvolume calls sumy_ibm
nchandle_error calls nf90_strerror
readinletfile calls excjs, yinterpolate, zinterpolate, zinterpolatet, zinterpolatew
readrestartfiles calls zinterpolate1d, zinterpolate2d, zinterpolatet1d, zinterpolatew1d
readzincoord calls mpi_bcast
slabsum calls mpi_allreduce
slabsumi calls mpi_allreduce
subgridnamelist calls mpi_bcast
uoutletarea calls sumy_ibm
voutletarea calls mpi_bcast
writestat_3d_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_3d_short_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
writestat_time_nc calls nf90_inq_varid, nf90_put_var, nf90_sync
excj calls mpi_sendrecv