calcfluidvolumes – uDALES
calcfluidvolumes Subroutine
11 statements
Source File
public subroutine calcfluidvolumes()
Uses
modfields
Arguments
None
Calls
Called by
Contents
Source Code
calcfluidvolumes
Source Code
  subroutine calcfluidvolumes
    !> calculates fluid volume and outlet areas, excluding blocks
    !> and saves it to variables from modfields
    use modfields, only : uoutarea, voutarea, fluidvol
    implicit none
    real :: volume
    ! calculate outlet area
    call uoutletarea(volume)
    uoutarea = volume
    ! calculate outlet area
    call voutletarea(volume)
    voutarea = volume
    ! calculate fluid volume
    call fluidvolume(volume)
    fluidvol = volume
  end subroutine calcfluidvolumes
Call graph
calcfluidvolumes calls fluidvolume, uoutletarea, voutletarea
fluidvolume calls sumy_ibm
uoutletarea calls sumy_ibm
voutletarea calls mpi_bcast
sumy_ibm calls mpi_allreduce
startup calls calcfluidvolumes
dalesurban calls startup