checksim – uDALES
checksim Subroutine
23 statements
Source File
public subroutine checksim()
Uses
modglobal
modmpi
Arguments
None
Calls
Called by
Contents
Source Code
checksim
Source Code
  subroutine checksim
    use modglobal, only : timee, rk3step, dt_lim,dt
    use modmpi,    only : myid
    implicit none
    character(20) :: timeday
    if (timee ==0.0) return
    if (rk3step/=3) return
    dtmn = dtmn +dt; ndt =ndt+1.
    if(timee<tnext) return
    tnext = tnext+tcheck
    dtmn  = dtmn / ndt
    if (myid==0) then
      call date_and_time(time=timeday)
      write (*,*) '================================================================='
      write (*,'(3A,F9.2,A,F12.9)') 'Time of Day: ', timeday(1:10),'    Time of Simulation: ', timee, '    dt: ',dtmn
    end if
    call calccourant
    call calcdiffnr
    call chkdiv
    dtmn  = 0.
    ndt   = 0.
  end subroutine checksim
Call graph
checksim calls calccourant, calcdiffnr, chkdiv
calccourant calls mpi_allreduce
calcdiffnr calls mpi_allreduce
chkdiv calls mpi_allreduce
dalesurban calls checksim