enthalpythickness – uDALES
enthalpythickness Subroutine
24 statements
Source File
public subroutine enthalpythickness(output, tinput, uinput)
Uses
modinletdata
modsurfdata
modglobal
modmpi
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: output
real, intent(in), dimension(kb:ke) :: tinput
real, intent(in), dimension(kb:ke) :: uinput
Called by
Contents
Source Code
enthalpythickness
Source Code
  subroutine enthalpythickness(output,tinput,uinput)
    use modglobal, only : jb,kb,ke,dzf !,Uinf
    use modinletdata, only : ubulk
    use modsurfdata, only : thls
    use modmpi, only    : myid
    implicit none
       real, dimension(kb:ke), intent(in) :: tinput  !< input temperature
       real, dimension(kb:ke), intent(in) :: uinput  !< input velocity
       real, intent(out)                  :: output  !< momentum thickness
       real, dimension(kb:ke)             :: ethick
       real thlsdummy
       integer :: k
       thlsdummy = thls
       if (tinput(ke) == thls) then
         thlsdummy = thls -0.000001
       end if
       do k=kb,ke
!         ethick(k) = (uinput(k)/uinput(ke)) * ((tinput(k) - tinput(ke)) /(thls - tinput(ke)))*dzf(k)
         ethick(k) = (uinput(k)/uinput(ke)) * ((tinput(k) - tinput(ke)) /(thlsdummy - tinput(ke)) )*dzf(k)
       end do
       output   = sum(ethick)  ! enthalpy thickness
       if (output==0.) then
         output= 0.000001
       end if
  end subroutine enthalpythickness
Call graph
inletgen calls enthalpythickness
boundary calls inletgen
readinitfiles calls boundary
dalesurban calls boundary, startup
startup calls readinitfiles