exitmodules – uDALES
exitmodules Subroutine
16 statements
Source File
public subroutine exitmodules()
Uses
modpois
modfields
modinlet
modmpi
modsubgrid
modthermodynamics
modglobal
Arguments
None
Calls
Called by
Contents
Source Code
exitmodules
Source Code
   subroutine exitmodules
      use modfields, only:exitfields
      use modglobal, only:exitglobal
      use modmpi, only:exitmpi
      use modpois, only:exitpois
      use modsubgrid, only:exitsubgrid
      use modthermodynamics, only:exitthermodynamics
      use modinlet, only:exitinlet
      call exitthermodynamics
      call exitsubgrid
      call exitpois
      call exitfields
      call exitglobal
      call exitinlet
      call exitmpi
   end subroutine exitmodules
Call graph
exitmodules calls exitfields, exitglobal, exitinlet, exitmpi, exitpois, exitsubgrid, exitthermodynamics
exitmpi calls mpi_comm_free, mpi_finalize, mpi_wtime
dalesurban calls exitmodules