exitfielddump – uDALES
exitfielddump Subroutine
6 statements
Source File
public subroutine exitfielddump()
Uses
modstat_nc
modglobal
Arguments
None
Calls
Called by
Contents
Source Code
exitfielddump
Source Code
  subroutine exitfielddump
      use modglobal, only : lfielddump
      use modstat_nc, only : exitstat_nc
    implicit none
       if (lfielddump) call exitstat_nc(ncid)
  end subroutine exitfielddump
Call graph
exitfielddump calls exitstat_nc
exitstat_nc calls nf90_close, nchandle_error
nchandle_error calls nf90_strerror
dalesurban calls exitfielddump