ibmwallfun – uDALES
ibmwallfun Subroutine
13 statements
Source File
public subroutine ibmwallfun()
Uses
modfields
modglobal
Arguments
None
Calls
Called by
Contents
Source Code
ibmwallfun
Source Code
   subroutine ibmwallfun
      use modglobal, only:libm
      use modfields, only:momfluxb, tfluxb, qfluxb
      if (libm) then
         ! compute fluxes at IBM
         momfluxb = 0.
         tfluxb = 0.
         qfluxb = 0.
         call xwallfun
         call ywallfunplus ! due to parallellisation differentiation between + and - side
         call ywallfunmin ! due to parallellisation differentiation between + and - side
         call zwallfun
      end if
   end subroutine ibmwallfun
Call graph
ibmwallfun calls xwallfun, ywallfunmin, ywallfunplus, zwallfun
xwallfun calls wfgr, wfmneutral, wfuno, xwallscalar
ywallfunmin calls wfgr, wfmneutral, wfuno, ywallscalarmin
ywallfunplus calls wfgr, wfmneutral, wfuno, ywallscalarplus
zwallfun calls wfgr, wfmneutral, wfuno, zwallscalar
wfuno calls unoh
dalesurban calls ibmwallfun