subgrid – uDALES
subgrid Subroutine
19 statements
Source File
public subroutine subgrid()
Uses
modfields
modsurfdata
modglobal
modmpi
Arguments
None
Calls
Called by
Contents
None
Call graph
subgrid calls closure, diffc, diffe, diffu, diffv, diffw, sources
closure calls closurebc
closurebc calls excjs
excjs calls mpi_sendrecv
dalesurban calls subgrid