sumy_ibm – uDALES
sumy_ibm Subroutine
12 statements
Source File
public subroutine sumy_ibm(sumy, var, ib, ie, jb, je, kb, ke, II)
Arguments
Type Intent Optional Attributes Name
real :: sumy(ib:ie,kb:ke)
real :: var(ib:ie,jb:je,kb:ke)
integer :: ib
integer :: ie
integer :: jb
integer :: je
integer :: kb
integer :: ke
integer :: II(ib:ie,jb:je,kb:ke)
Calls
Called by
Contents
Source Code
sumy_ibm
Source Code
  subroutine sumy_ibm(sumy,var,ib,ie,jb,je,kb,ke,II)
    ! This routine sums up a variable over the y direction,
    ! only including the fluid cells.
    implicit none
    integer                 :: ib,ie,jb,je,kb,ke
    real                    :: sumy(ib:ie,kb:ke)
    real                    :: sumproc(ib:ie,kb:ke)
    real                    :: var(ib:ie,jb:je,kb:ke)
    integer                 :: II(ib:ie,jb:je,kb:ke)
    sumproc = 0.
    sumy  = 0.
    sumproc = sum(var(ib:ie,jb:je,kb:ke)*II(ib:ie,jb:je,kb:ke), DIM=2)
    call MPI_ALLREDUCE(sumproc(ib:ie,kb:ke), sumy(ib:ie,kb:ke), (ke-kb+1)*(ie-ib+1), MY_REAL,MPI_SUM, comm3d,mpierr)
    end subroutine sumy_ibm
Call graph
sumy_ibm calls mpi_allreduce
fluidvolume calls sumy_ibm
masscorr calls sumy_ibm
uoutletarea calls sumy_ibm
calcfluidvolumes calls fluidvolume, uoutletarea
dalesurban calls masscorr, startup
startup calls calcfluidvolumes