uoutletarea – uDALES
uoutletarea Subroutine
15 statements
Source File
public subroutine uoutletarea(area)
Uses
modfields
modglobal
modmpi
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: area
Calls
Called by
Contents
Source Code
uoutletarea
Source Code
  subroutine uoutletarea(area)
    ! calculates outlet area of domain for u-velocity excluding blocks
    use modglobal, only   : ib,ie,jb,je,kb,ke,dy,dzf
    use modfields, only   : IIc
    use modmpi, only      : sumy_ibm
    implicit none
    real, intent(out)       :: area
    real, dimension(kb:ke)  :: sumy
    integer                    k
    sumy = 0.
    ! integrate fluid area at outflow plane in y
    call sumy_ibm(sumy,IIc(ie,jb:je,kb:ke)*dy,ie,ie,jb,je,kb,ke,IIc(ie,jb:je,kb:ke))
    ! integrate fluid area at outflow plane in z
    do k=kb,ke
      sumy(k) = sumy(k)*dzf(k)
    end do
    area = sum(sumy(kb:ke))
  end subroutine uoutletarea
Call graph
uoutletarea calls sumy_ibm
sumy_ibm calls mpi_allreduce
calcfluidvolumes calls uoutletarea
startup calls calcfluidvolumes
dalesurban calls startup