writestat_dims_nc – uDALES
writestat_dims_nc Subroutine
26 statements
Source File
public subroutine writestat_dims_nc(ncid)
Uses
modglobal
modmpi
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
Calls
Called by
Contents
Source Code
writestat_dims_nc
Source Code
  subroutine writestat_dims_nc(ncid)
    use modglobal, only : xf,xh,dy,zf,zh,jmax
    use modmpi, only : myid
    implicit none
    integer, intent(in) :: ncid
    integer             :: i=0,iret,length,varid
    write(*,*) 'writestat_dims_nc'
    iret = nf90_inq_varid(ncid, 'xt', VarID)
    if (iret==0) iret=nf90_inquire_dimension(ncid, xtID, len=length)
    !if (iret==0) iret = nf90_put_var(ncid, varID, zf(1:length),(/1/))
    if (iret==0) iret = nf90_put_var(ncid, varID, xf(1:length),(/1/))
    iret = nf90_inq_varid(ncid, 'xm', VarID)
    if (iret==0) iret=nf90_inquire_dimension(ncid, xmID, len=length)
    if (iret==0) iret = nf90_put_var(ncid, varID, xh(1:length),(/1/))
    iret = nf90_inq_varid(ncid, 'yt', VarID)
    if (iret==0) iret=nf90_inquire_dimension(ncid, ytID, len=length)
    if (iret==0) iret = nf90_put_var(ncid, varID, (/(dy*(0.5+i)+myid*jmax*dy,i=0,length-1)/),(/1/))
    iret = nf90_inq_varid(ncid, 'ym', VarID)
    if (iret==0) iret=nf90_inquire_dimension(ncid, ymID, len=length)
    if (iret==0) iret = nf90_put_var(ncid, varID, (/(dy*i+myid*jmax*dy,i=0,length-1)/),(/1/))
    iret = nf90_inq_varid(ncid, 'zt', VarID)
    if (iret==0) iret=nf90_inquire_dimension(ncid,ztID, len=length)
    if (iret==0) iret = nf90_put_var(ncid, varID, zf(0:length-1),(/1/))  !ils13, 29.06.2017 zf starts at 0, not at 1
    iret = nf90_inq_varid(ncid, 'zm', VarID)
    if (iret==0) iret=nf90_inquire_dimension(ncid, zmID, len=length)
    if (iret==0) iret = nf90_put_var(ncid, varID, zh(0:length-1),(/1/))  !same for zh
    !if (isurf==1) then
      !iret = nf90_inq_varid(ncid, 'zts', VarID)
      !if (iret==0) iret = nf90_inquire_dimension(ncid, ztsID, len=length)
      !if (iret==0) iret = nf90_put_var(ncid, varID, zsoilc(1:length),(/1/))
    !end if
  end subroutine writestat_dims_nc
Call graph
writestat_dims_nc calls nf90_inq_varid, nf90_inquire_dimension, nf90_put_var
initeb calls writestat_dims_nc
initfielddump calls writestat_dims_nc
initstatsdump calls writestat_dims_nc
dalesurban calls initeb, initfielddump, initstatsdump