writeinletfile – uDALES
writeinletfile Subroutine
28 statements
Source File
public subroutine writeinletfile()
Uses
modglobal
modmpi
Arguments
None
Called by
Contents
Source Code
writeinletfile
Source Code
  subroutine writeinletfile
    use modglobal, only : jb,je,kb,ke,cexpnr,ifoutput,nstore,ltempeq
    use modmpi,    only : cmyid,myid
!    use modinletdata, only : storeu0inletbc,storev0inletbc,storew0inletbc,nfile
    implicit none
    integer fileid
    integer j,k,n
    character(24) name
      name = 'inlet/inlet_    k   .'
      write (name(13:16)  ,'(i4.4)') nfile
      name(18:20)= cmyid
      name(22:24)= cexpnr
      write(6,*) 'Writing Inlet velocity: ', name
      open  (ifoutput,file=name,form='unformatted',position='append')
      write(ifoutput)  (((storeu0inletbc (j,k,n),j=jb,je),k=kb,ke),  n=1,nstore)
      write(ifoutput)  (((storev0inletbc (j,k,n),j=jb,je),k=kb,ke),  n=1,nstore)
      write(ifoutput)  (((storew0inletbc (j,k,n),j=jb,je),k=kb,ke+1),n=1,nstore)
      close (ifoutput)
      if (ltempeq ) then
        name = 'inlet/itemp_    k   .'
        write (name(13:16)  ,'(i4.4)') nfile
        name(18:20)= cmyid
        name(22:24)= cexpnr
        write(6,*) 'Writing Inlet temperature: ', name
        open  (ifoutput,file=name,form='unformatted',position='append')
        write(ifoutput)  (((storet0inletbc (j,k,n),j=jb,je),k=kb,ke),  n=1,nstore)
        close (ifoutput)
      end if
  end subroutine writeinletfile
Call graph
inletgen calls writeinletfile
inletgennotemp calls writeinletfile
boundary calls inletgen, inletgennotemp
readinitfiles calls boundary
dalesurban calls boundary, startup
startup calls readinitfiles