zwallfun – uDALES
zwallfun Subroutine
57 statements
Source File
public subroutine zwallfun()
Uses
modfields
initfac
modglobal
modmpi
Arguments
None
Calls
Called by
Contents
Source Code
zwallfun
Source Code
   subroutine zwallfun
      use modglobal, only:dzf, dzfi, dzhi, dzhiq, dxf, dxfi, dxhi, dyi, nsv, lles, numol, ltempeq, lmoist, &
         ih, jh, kh, ihc, jhc, khc, iwallmom, iwalltemp, iwallmoist, iwallscal
      use modfields, only:u0, v0, up, vp, shear, thl0, thlp, qt0, qtp, sv0, svp, tfluxb, momfluxb, exnf, cth, qfluxb
      use modmpi, only:myid
      use initfac, only:fachf, block, faclGR, facef, facqsat, fachurel, facf, facT, facz0, facz0h
      integer i, j, k, n, nc, il, iu, jl, ju, im, jm, km, m
      if (iwallmom == 1) then
      !fixed flux
      else if (iwallmom == 2) then
         do n = 1, nxwall
            k = block(ixwall(n), 7)
            call wfuno(ih, jh, kh, up, vp, thlp, momfluxb, tfluxb, cth, bcTfluxA, u0, v0, thl0, facT(k, 1), facz0(k), facz0h(k), ixwall(n), 1, 51)
         end do
      else if (iwallmom == 3) then
         do n = 1, nxwall
            k = block(ixwall(n), 7)
            call wfmneutral(ih, jh, kh, up, vp, momfluxb, u0, v0, facz0(k), ixwall(n), 1, 51)
         end do
      end if
      if (ltempeq) then
      if (iwalltemp == 1) then
         do n = 1, nxwall ! loop over all shear x-walls
            call zwallscalar(ih, jh, kh, thl0, thlp, bctfz, ixwall(n))
         end do
      else if (iwalltemp == 2) then
         do n = 1, nxwall
            k = block(ixwall(n), 7)
            call wfuno(ih, jh, kh, up, vp, thlp, momfluxb, tfluxb, cth, bcTfluxA, u0, v0, thl0, facT(k, 1), facz0(k), facz0h(k), ixwall(n), 1, 52)
            fachf(k) = fachf(k) + bcTfluxA
         end do
      end if
      end if
      if (lmoist) then
      if (iwallmoist == 1) then
         do n = 1, nxwall ! loop over all shear x-walls
            call zwallscalar(ih, jh, kh, qt0, qtp, bcqfz, ixwall(n))
         end do
      end if
      if ((ltempeq) .and. (iwallmoist == 2)) then
         do n = 1, nxwall
            k = block(ixwall(n), 7)
            if (faclGR(k)) then
           call wfGR(ih, jh, kh, qtp, qfluxb, cth, bcqfluxA, qt0, facqsat(k), fachurel(k), facf(k, 4), facf(k, 5), ixwall(n), 1, 52)
                facef(k) = facef(k) + bcqfluxA
            end if
         end do
      end if
      end if
      if (nsv>0) then
      if (iwallscal == 1) then
         do n = 1, nxwall ! loop over all shear x-walls
            do m = 1, nsv
               call zwallscalar(ihc, jhc, khc, sv0(:,:,:,m), svp(:,:,:,m), 0., ixwall(n))
            end do
         end do
      end if
      end if
   end subroutine zwallfun
Call graph
zwallfun calls wfgr, wfmneutral, wfuno, zwallscalar
wfuno calls unoh
ibmwallfun calls zwallfun
dalesurban calls ibmwallfun